bittrex:
  GET_markets_url: https://api.bittrex.com/v3/markets
  GET_markets_summary_url: https://api.bittrex.com/v3/markets/summaries
  GET_market_symbol_url: https://api.bittrex.com/v3/markets/{market_symbol}
  GET_market_symbol_summary_url: https://api.bittrex.com/v3/markets/{market_symbol}/summary

binance:
  GET_markets_url:
  GET_markets_summary_url:
  GET_market_symbol_url:
  GET_market_symbol_summary_url:

poloniex:
  GET_markets_url:
  GET_markets_summary_url: https://poloniex.com/public?command=returnTicker
  GET_market_symbol_url:
  GET_market_symbol_summary_url:

